### ISSUE TITLE
Laravel API Go!

### ISSUE THREAD

**Issue by codesktop** [matttrix/________t#2]
```
| POST     | email/verification-notification | Laravel\Fortify\Http\Controllers\EmailVerificationNotificationController@store |
| GET|HEAD | email/verify                    | Laravel\Fortify\Http\Controllers\EmailVerificationPromptController@__invoke    |
| GET|HEAD | email/verify/{id}/{hash}        | Laravel\Fortify\Http\Controllers\VerifyEmailController@__invoke                |
| POST     | logout                          | Laravel\Fortify\Http\Controllers\AuthenticatedSessionController@destroy        |
| GET|HEAD | user/confirm-password           | Laravel\Fortify\Http\Controllers\ConfirmablePasswordController@show            |
| POST     | user/confirm-password           | Laravel\Fortify\Http\Controllers\ConfirmablePasswordController@store           |
| GET|HEAD | user/confirmed-password-status  | Laravel\Fortify\Http\Controllers\ConfirmedPasswordStatusController@show        |
| PUT      | user/password                   | Laravel\Fortify\Http\Controllers\PasswordController@update                     |
```

**Comment by codesktop** [comment]
```
http://localhost:8000/user/profile
Update Password
  Current Password
  New Password
  Confirm Password
  SAVE
    current_password: ""
    password: ""
    password_confirmation: ""
http://localhost:8000/email/verify
  Request URL: http://localhost:8000/email/verification-notification
  Request Method: POST
http://localhost:8000/user/confirmed-password-status
Laravel\Fortify\Http\Controllers\PasswordResetLinkController@create
Laravel\Fortify\Http\Controllers\AuthenticatedSessionController@create
vite.config.js
Route::get('/dashboard', function () {})->middleware(['verified']);
```

**Comment by codesktop** [comment]
**Tokens**


```
http://p2.music.126.net/xwnMQLfgcJ4Q1tUULDlAaA==/109951163027164025.jpg

use Laravel\Sanctum\HasApiTokens;
class User extends Authenticatable
{
  use HasApiTokens, HasFactory, Notifiable;
}
$token = $user->createToken('token-name');
return $token->plainTextToken;
return $user->createToken('token-name', ['server:update'])->plainTextToken;
if ($user->tokenCan('server:update')) {}
// Revoke all tokens...
$user->tokens()->delete();
// Revoke the user's current token...
$request->user()->currentAccessToken()->delete();
// Revoke a specific token...
$user->tokens()->where('id', $id)->delete();
```

**Comment by codesktop** [comment]
**Names**

```
permissions
  name
  text
  deprecated
user_permissions
  user_id
  name
  disabled
role_permissions
  role_id
  permission_id
roles
  name
  text
blog_posts
global_configs
```

**Comment by codesktop** [comment]
```
version: '3.8'

networks:
  laravel_networks:

services:
  nginx1:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www

  laravel:
    build: .
    volumes:
      - .:/var/www
    networks:
      - laravel_networks
    depends_on:
      - postgres
      - redis
    ports:
      - '9000:9000'

  postgres:
    image: postgres
    restart: always
    networks:
      - laravel_networks
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file: .env
    # environment:
    #   POSTGRES_DB: asdsd
    #   POSTGRES_USER: asdasd
    #   POSTGRES_PASSWORD: asdasd
    ports:
      - '5432:5432'

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - laravel_networks

```
